script:
  - echo 'Code checking...'
  - RAILS_ENV=development bundle exec rubocop  --parallel -l
  - echo 'code checking completed'
  - echo 'Test Cases running step...'
  - RAILS_ENV=test bundle exec rspec spec/
  - echo 'Test cases completed'